### ISSUE TITLE
Trabajar en application.properties

### ISSUE THREAD

**Issue by NestorCorimayo** [FernandoValero/Trabajo-Practico-Final#16]
Agregar las dependencias necesarias para el properties.

**Comment by Evelin-Rocha** [comment]
Issue recibida. Gracias @NestorCorimayo

**Comment by Evelin-Rocha** [comment]
Dependencias agregadas.

[Agregar_dependencias_archivo_properties](https://github.com/FernandoValero/Trabajo-Practico-Final/tree/Agregar_dependencias_archivo_properties)

**Comment by Evelin-Rocha** [comment]
Corrección en archivo application.properties.

**Comment by Evelin-Rocha** [comment]
Correcciones realizadas.
[Correccion_en_applicationProperties](https://github.com/FernandoValero/Trabajo-Practico-Final/tree/Correccion_en_applicationProperties)
