### ISSUE TITLE
Creación de layout nav

### ISSUE THREAD

**Issue by FernandoValero** [FernandoValero/Trabajo-Practico-Final#19]
Incorporar el uso del layout nav para ser usado en las páginas que la necesiten.

**Comment by FernandoValero** [comment]
Se agrego el layout nav.
Se espera revisión @SebasFarfan. 
Rama: [creacion_layout_nav](https://github.com/FernandoValero/Trabajo-Practico-Final/tree/creacion_layout_nav)

**Comment by SebasFarfan** [comment]
Se revisó. agregar "th:fragment="nav" y con eso funcionará. @FernandoValero

**Comment by FernandoValero** [comment]
Se corrigió el error del archivo nav.html tomando en cuenta la revisión.
Rama en la que se trabajo: [modificacion_layout_nav](https://github.com/FernandoValero/Trabajo-Practico-Final/tree/modificacion_layout_nav)
